import {sb} from './supabase.js';
const $=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let disciplines=[],topics=[],materials=[],draft=[];
function notice(m,t='success'){const e=$('#theoryAdminNotice');if(!e)return;e.textContent=m;e.className=`notice ${t}`;e.classList.remove('hidden');clearTimeout(notice.t);notice.t=setTimeout(()=>e.classList.add('hidden'),4000)}
const norm=s=>(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
function fill(){const opts=disciplines.map(d=>`<option value="${d.id}">${esc(d.nome)}</option>`).join('');$('#theoryAdminDiscipline').innerHTML='<option value="">Selecione…</option>'+opts;$('#theoryAdminFilter').innerHTML='<option value="">Todas as disciplinas</option>'+opts;fillTopics()}
function fillTopics(){const did=Number($('#theoryAdminDiscipline')?.value)||0;$('#theoryAdminTopic').innerHTML='<option value="">Visão geral da disciplina</option>'+topics.filter(t=>Number(t.disciplina_id)===did).map(t=>`<option value="${t.id}">${esc(t.nome)}</option>`).join('')}
function reset(){const f=$('#theoryMaterialForm');f.reset();f.elements.id.value='';f.elements.ativo.checked=true;$('#cancelTheoryMaterial').classList.add('hidden');fillTopics()}
function render(){const q=($('#theoryAdminSearch')?.value||'').toLowerCase(),did=Number($('#theoryAdminFilter')?.value)||0;const list=materials.filter(m=>(!did||Number(m.disciplina_id)===did)&&(!q||`${m.titulo} ${m.disciplinas?.nome||''} ${m.assuntos?.nome||''}`.toLowerCase().includes(q)));const host=$('#theoryAdminList');if(!list.length){host.innerHTML='<div class="card empty">Nenhum material encontrado.</div>';return}host.innerHTML=list.map(m=>`<article class="card theory-admin-item"><div><span class="badge ${m.ativo?'ok':'off'}">${m.ativo?'ATIVO':'OCULTO'}</span><h3>${esc(m.titulo)}</h3><small>${esc(m.disciplinas?.nome||'')}${m.assuntos?.nome?' · '+esc(m.assuntos.nome):''}</small><p>${esc(m.resumo||'')}</p></div><div class="actions"><button class="mini" data-theory-edit="${m.id}">EDITAR</button><button class="mini" data-theory-toggle="${m.id}">${m.ativo?'OCULTAR':'PUBLICAR'}</button><button class="mini danger-mini" data-theory-delete="${m.id}">EXCLUIR</button></div></article>`).join('')}
async function load(){const [{data:d,error:de},{data:t,error:te},{data:m,error:me}]=await Promise.all([sb.from('disciplinas').select('id,nome').eq('ativo',true).order('nome'),sb.from('assuntos').select('id,nome,disciplina_id').eq('ativo',true).order('nome'),sb.from('teoria_materiais').select('*,disciplinas(nome),assuntos(nome)').order('ordem').order('titulo')]);if(de||te||me){notice('Não foi possível carregar a Teoria Direcionada. Execute o SQL da V4.1.','error');return}disciplines=d||[];topics=t||[];materials=m||[];fill();render()}
function parseBlocks(v){if(!v.trim())return[];const a=JSON.parse(v);if(!Array.isArray(a))throw new Error('Blocos precisam ser um array JSON.');return a}
async function save(e){e.preventDefault();const f=e.currentTarget;let blocos;try{blocos=parseBlocks(f.elements.blocos.value)}catch(err){return notice(err.message,'error')}const payload={disciplina_id:Number(f.elements.disciplina_id.value),assunto_id:f.elements.assunto_id.value?Number(f.elements.assunto_id.value):null,titulo:f.elements.titulo.value.trim(),subtitulo:f.elements.subtitulo.value.trim()||null,resumo:f.elements.resumo.value.trim()||null,fonte_nome:f.elements.fonte_nome.value.trim()||null,fonte_url:f.elements.fonte_url.value.trim()||null,blocos,ativo:f.elements.ativo.checked,updated_at:new Date().toISOString()};if(!payload.disciplina_id||!payload.titulo)return;const id=Number(f.elements.id.value)||null;const {error}=id?await sb.from('teoria_materiais').update(payload).eq('id',id):await sb.from('teoria_materiais').insert(payload);if(error)return notice(error.message,'error');notice(id?'Material atualizado.':'Material criado.');reset();await load()}
function edit(id){const m=materials.find(x=>Number(x.id)===Number(id));if(!m)return;const f=$('#theoryMaterialForm');f.elements.id.value=m.id;f.elements.disciplina_id.value=m.disciplina_id;fillTopics();f.elements.assunto_id.value=m.assunto_id||'';for(const k of ['titulo','subtitulo','resumo','fonte_nome','fonte_url'])f.elements[k].value=m[k]||'';f.elements.blocos.value=JSON.stringify(m.blocos||[],null,2);f.elements.ativo.checked=!!m.ativo;$('#cancelTheoryMaterial').classList.remove('hidden');f.scrollIntoView({behavior:'smooth'})}
function analyze(){draft=[];let parsed;try{parsed=JSON.parse($('#theoryJsonImport').value)}catch(e){$('#theoryJsonPreview').innerHTML='<div class="notice error">JSON inválido.</div>';$('#importTheoryJson').disabled=true;return}const arr=Array.isArray(parsed)?parsed:parsed.materiais;if(!Array.isArray(arr)){return notice('O JSON precisa conter o array materiais.','error')}draft=arr.map((m,i)=>{const d=disciplines.find(x=>norm(x.nome)===norm(m.disciplina)),t=topics.find(x=>Number(x.disciplina_id)===Number(d?.id)&&norm(x.nome)===norm(m.assunto));const errors=[];if(!d)errors.push('disciplina não encontrada');if(m.assunto&&!t)errors.push('assunto não encontrado');if(!m.titulo)errors.push('título ausente');if(!Array.isArray(m.blocos))errors.push('blocos inválidos');return {...m,_i:i,_disc:d,_topic:t,_errors:errors}});const ok=draft.filter(x=>!x._errors.length).length;$('#theoryJsonPreview').innerHTML=`<div class="notice ${ok===draft.length?'success':'warn'}"><b>${ok}/${draft.length}</b> material(is) prontos para importar.</div>`+draft.map(x=>`<div class="theory-json-line ${x._errors.length?'bad':''}"><b>${esc(x.titulo||`Material ${x._i+1}`)}</b><small>${x._errors.length?esc(x._errors.join(' · ')):`${esc(x.disciplina)}${x.assunto?' · '+esc(x.assunto):''}`}</small></div>`).join('');$('#importTheoryJson').disabled=!ok}
async function importDraft(){const rows=draft.filter(x=>!x._errors.length).map((x,i)=>({disciplina_id:x._disc.id,assunto_id:x._topic?.id||null,titulo:x.titulo,subtitulo:x.subtitulo||null,resumo:x.resumo||null,blocos:x.blocos,fonte_nome:x.fonte_nome||null,fonte_url:x.fonte_url||null,ordem:Number(x.ordem)||i+1,ativo:x.ativo!==false,updated_at:new Date().toISOString()}));if(!rows.length)return;const {error}=await sb.from('teoria_materiais').insert(rows);if(error)return notice(error.message,'error');notice(`${rows.length} material(is) importado(s).`);$('#theoryJsonImport').value='';$('#theoryJsonPreview').innerHTML='';$('#importTheoryJson').disabled=true;draft=[];await load()}
export async function setupAdminTeoria(){await load();$('#theoryAdminDiscipline')?.addEventListener('change',fillTopics);$('#theoryMaterialForm')?.addEventListener('submit',save);$('#cancelTheoryMaterial')?.addEventListener('click',reset);$('#newTheoryMaterial')?.addEventListener('click',()=>{reset();$('#theoryMaterialForm').scrollIntoView({behavior:'smooth'})});$('#theoryAdminSearch')?.addEventListener('input',render);$('#theoryAdminFilter')?.addEventListener('change',render);$('#analyzeTheoryJson')?.addEventListener('click',analyze);$('#importTheoryJson')?.addEventListener('click',importDraft);$('#theoryAdminList')?.addEventListener('click',async e=>{const ed=e.target.closest('[data-theory-edit]')?.dataset.theoryEdit,tg=e.target.closest('[data-theory-toggle]')?.dataset.theoryToggle,del=e.target.closest('[data-theory-delete]')?.dataset.theoryDelete;if(ed)return edit(ed);if(tg){const m=materials.find(x=>Number(x.id)===Number(tg));const {error}=await sb.from('teoria_materiais').update({ativo:!m.ativo,updated_at:new Date().toISOString()}).eq('id',m.id);if(error)return notice(error.message,'error');return load()}if(del){if(!confirm('Excluir este material teórico?'))return;const {error}=await sb.from('teoria_materiais').delete().eq('id',Number(del));if(error)return notice(error.message,'error');return load()}})}
