import {sb} from './supabase.js';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let cards=[],disciplines=[],topics=[];
function fill(){
 const f=$('#officialFlashForm');if(!f)return;
 const d=f.elements.disciplina_id,cur=d.value;d.innerHTML='<option value="">Selecione...</option>'+disciplines.filter(x=>x.ativo).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if(disciplines.some(x=>String(x.id)===cur))d.value=cur;fillTopics();
 const fil=$('#adminFlashDiscipline'),fc=fil.value;fil.innerHTML='<option value="">Todas</option>'+disciplines.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');if(disciplines.some(x=>String(x.id)===fc))fil.value=fc;
}
function fillTopics(){const f=$('#officialFlashForm');if(!f)return;const s=f.elements.assunto_id,did=Number(f.elements.disciplina_id.value||0),cur=s.value;s.innerHTML='<option value="">Sem assunto específico</option>'+topics.filter(t=>!did||Number(t.disciplina_id)===did).map(t=>`<option value="${t.id}">${esc(t.nome)}</option>`).join('');if(topics.some(t=>String(t.id)===cur))s.value=cur}
function render(){const box=$('#officialFlashList'),q=($('#adminFlashSearch').value||'').toLowerCase(),did=Number($('#adminFlashDiscipline').value||0),status=$('#adminFlashStatus').value;const list=cards.filter(c=>(!q||`${c.frente} ${c.verso}`.toLowerCase().includes(q))&&(!did||Number(c.disciplina_id)===did)&&(status==='todos'||(status==='ativo')===!!c.ativo));$('#adminFlashCount').textContent=list.length;box.innerHTML=list.length?list.map(c=>`<article class="card admin-flash-item ${c.ativo?'':'is-inactive'}"><div><div class="admin-question-meta"><span>${esc(c.disciplinas?.nome||'')}</span>${c.assuntos?.nome?`<span>${esc(c.assuntos.nome)}</span>`:''}<span>R ${c.recorrencia||3}</span><span>D ${c.dificuldade||3}</span></div><b>${esc(c.frente)}</b><p>${esc(c.verso)}</p></div><div class="actions"><button class="mini" data-edit-flash="${c.id}">Editar</button><button class="mini" data-toggle-flash="${c.id}">${c.ativo?'Desativar':'Ativar'}</button><button class="mini danger-mini" data-delete-flash="${c.id}">Excluir</button></div></article>`).join(''):'<div class="card empty">Nenhum flashcard encontrado.</div>'}
function reset(){const f=$('#officialFlashForm');f.reset();f.elements.id.value='';f.elements.recorrencia.value=3;f.elements.dificuldade.value=3;$('#cancelOfficialFlash').classList.add('hidden');fill()}
async function load(){const [{data:c,error},{data:d},{data:t}]=await Promise.all([sb.from('flashcards').select('id,disciplina_id,assunto_id,frente,verso,recorrencia,dificuldade,ativo,created_at,disciplinas(nome),assuntos(nome)').is('user_id',null).order('created_at',{ascending:false}),sb.from('disciplinas').select('*').order('ordem').order('nome'),sb.from('assuntos').select('*').order('nome')]);if(error)return;cards=c||[];disciplines=d||[];topics=t||[];fill();render()}
export async function setupAdminFlashcards(ctx,notice){
 const form=$('#officialFlashForm');if(!form)return;
 form.elements.disciplina_id.addEventListener('change',fillTopics);$('#adminFlashSearch').addEventListener('input',render);$('#adminFlashDiscipline').addEventListener('change',render);$('#adminFlashStatus').addEventListener('change',render);$('#cancelOfficialFlash').addEventListener('click',reset);
 form.addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,p={disciplina_id:Number(f.elements.disciplina_id.value),assunto_id:f.elements.assunto_id.value?Number(f.elements.assunto_id.value):null,frente:f.elements.frente.value.trim(),verso:f.elements.verso.value.trim(),recorrencia:Number(f.elements.recorrencia.value)||3,dificuldade:Number(f.elements.dificuldade.value)||3,ativo:true,created_by:ctx.user.id,user_id:null};const r=id?await sb.from('flashcards').update(p).eq('id',id).is('user_id',null):await sb.from('flashcards').insert(p);if(r.error)return notice('Não foi possível salvar o flashcard.','error');notice(id?'Flashcard atualizado.':'Flashcard cadastrado.');reset();await load()});
 $('#officialFlashList').addEventListener('click',async e=>{const eb=e.target.closest('[data-edit-flash]'),tb=e.target.closest('[data-toggle-flash]'),db=e.target.closest('[data-delete-flash]');if(eb){const c=cards.find(x=>Number(x.id)===Number(eb.dataset.editFlash)),f=form;f.elements.id.value=c.id;f.elements.disciplina_id.value=c.disciplina_id;fillTopics();f.elements.assunto_id.value=c.assunto_id||'';f.elements.frente.value=c.frente;f.elements.verso.value=c.verso;f.elements.recorrencia.value=c.recorrencia||3;f.elements.dificuldade.value=c.dificuldade||3;$('#cancelOfficialFlash').classList.remove('hidden');f.scrollIntoView({behavior:'smooth'})}if(tb){const c=cards.find(x=>Number(x.id)===Number(tb.dataset.toggleFlash));const {error}=await sb.from('flashcards').update({ativo:!c.ativo}).eq('id',c.id).is('user_id',null);if(error)return notice('Não foi possível alterar o flashcard.','error');notice(c.ativo?'Flashcard desativado.':'Flashcard ativado.');await load()}if(db){const c=cards.find(x=>Number(x.id)===Number(db.dataset.deleteFlash));if(!confirm('Excluir este flashcard oficial?'))return;const {error}=await sb.from('flashcards').delete().eq('id',c.id).is('user_id',null);if(error)return notice('Não foi possível excluir o flashcard.','error');notice('Flashcard excluído.');await load()}});
 await load();
}
