import {sb} from './supabase.js';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let rows=[];
function fmt(v){return v?new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—'}
function fmtDate(v){return v?new Date(v).toLocaleDateString('pt-BR'):'—'}
function pct(v){const n=Number(v);return Number.isFinite(n)?`${Math.round(n)}%`:'0%'}
function render(){const q=($('#trackSearch')?.value||'').toLowerCase(),f=$('#trackFilter')?.value||'todos',now=Date.now(),week=7*86400000;const list=rows.filter(r=>{const hit=(r.nome||'').toLowerCase().includes(q)||(r.email||'').toLowerCase().includes(q);const active7=r.ultima_atividade&&now-new Date(r.ultima_atividade).getTime()<=week;return hit&&(f==='todos'||f==='ativos7'&&active7||f==='inativos7'&&!active7)});$('#studentTrackingRows').innerHTML=list.length?list.map(r=>`<tr><td><b>${esc(r.nome||'Participante')}</b><br><small class="muted">${esc(r.email||'')}</small></td><td>${fmt(r.ultima_atividade)}</td><td>${r.questoes_7d||0}</td><td>${Number(r.aproveitamento_7d||0).toFixed(0)}%</td><td>${r.missoes_7d||0}</td><td>${r.simulados_30d||0}</td><td><button class="mini" data-student-detail="${esc(r.email||'')}">Ver aluno</button></td></tr>`).join(''):'<tr><td colspan="7"><div class="empty compact">Nenhum aluno encontrado.</div></td></tr>';$('#trackActive').textContent=rows.length;$('#trackStudied7').textContent=rows.filter(r=>r.ultima_atividade&&now-new Date(r.ultima_atividade).getTime()<=week).length;$('#trackQuestions7').textContent=rows.reduce((a,b)=>a+Number(b.questoes_7d||0),0);$('#trackSims30').textContent=rows.reduce((a,b)=>a+Number(b.simulados_30d||0),0)}
function closeDetail(){const m=$('#studentDetailModal');if(m)m.classList.add('hidden')}
function bars(items=[]){if(!items.length)return '<div class="empty compact">Ainda não há dados suficientes.</div>';return items.map(x=>`<div class="student-progress-row"><div><b>${esc(x.nome||'Sem identificação')}</b><small>${Number(x.total||0)} questões · ${Number(x.acertos||0)} acertos</small></div><strong>${pct(x.aproveitamento)}</strong><div class="progress"><i style="width:${Math.max(0,Math.min(100,Number(x.aproveitamento)||0))}%"></i></div></div>`).join('')}
function simulations(items=[]){if(!items.length)return '<div class="empty compact">Nenhum simulado finalizado.</div>';return items.map(x=>`<div class="student-sim-row"><div><b>${esc(x.titulo||'Simulado')}</b><small>${fmtDate(x.finalizada_em)}</small></div><strong>${x.pontuacao===null||x.pontuacao===undefined?'—':`${Number(x.pontuacao).toFixed(1)}%`}</strong></div>`).join('')}
function activity(items=[]){if(!items.length)return '<div class="empty compact">Sem atividade recente.</div>';return items.map(x=>`<div class="student-activity-day"><span>${fmtDate(x.data)}</span><b>${Number(x.questoes||0)} questões</b><small>${Number(x.flashcards||0)} cards · ${Number(x.missoes||0)} missões · ${Number(x.simulados||0)} simulados</small></div>`).join('')}
function showDetail(data){const box=$('#studentDetailContent');if(!box)return;const p=data?.perfil||{},r=data?.resumo||{};box.innerHTML=`<div class="section-title compact-title"><div><span class="eyebrow">ACOMPANHAMENTO INDIVIDUAL</span><h2 id="studentDetailTitle">${esc(p.nome||'Aluno')}</h2><span class="muted">${esc(p.email||'')}</span></div><button id="closeStudentDetail" class="mini" type="button">FECHAR</button></div><section class="grid student-detail-stats"><div class="card stat"><span>📝 Questões</span><b>${Number(r.questoes_total||0)}</b><small>${pct(r.aproveitamento_geral)} de aproveitamento</small></div><div class="card stat"><span>🔥 Sequência atual</span><b>${Number(r.sequencia_atual||0)} dias</b><small>Melhor: ${Number(r.melhor_sequencia||0)} dias</small></div><div class="card stat"><span>🧠 Flashcards 30d</span><b>${Number(r.flashcards_30d||0)}</b><small>${Number(r.dias_ativos_30d||0)} dias ativos no período</small></div><div class="card stat"><span>🎯 Missões 30d</span><b>${Number(r.missoes_30d||0)}</b><small>${Number(r.simulados_total||0)} simulados finalizados</small></div></section><div class="student-detail-grid"><div class="card"><div class="section-title compact-title"><h3>Desempenho por disciplina</h3></div>${bars(data?.disciplinas||[])}</div><div class="card"><div class="section-title compact-title"><h3>Assuntos para reforço</h3></div>${bars(data?.assuntos_reforco||[])}</div></div><div class="student-detail-grid"><div class="card"><div class="section-title compact-title"><h3>Simulados recentes</h3></div>${simulations(data?.simulados_recentes||[])}</div><div class="card"><div class="section-title compact-title"><h3>Atividade recente</h3></div><div class="student-activity-list">${activity(data?.atividade_recente||[])}</div></div></div>`;$('#closeStudentDetail')?.addEventListener('click',closeDetail,{once:true})}
async function openDetail(email){if(!email)return;const modal=$('#studentDetailModal'),box=$('#studentDetailContent');modal?.classList.remove('hidden');if(box)box.innerHTML='<div class="empty compact">Carregando acompanhamento do aluno…</div>';const {data,error}=await sb.rpc('admin_detalhe_aluno',{p_email:email});if(error){console.error(error);if(box)box.innerHTML='<div class="section-title"><h3>Não foi possível carregar o aluno</h3><button class="mini" id="closeStudentDetail">FECHAR</button></div><div class="empty compact">Execute o SQL da V2.3 no banco e tente novamente.</div>';$('#closeStudentDetail')?.addEventListener('click',closeDetail,{once:true});return}showDetail(data||{})}
async function load(){const btn=$('#refreshStudentTracking');if(btn){btn.disabled=true;btn.textContent='ATUALIZANDO...'}const {data,error}=await sb.rpc('admin_acompanhamento_alunos');if(btn){btn.disabled=false;btn.textContent='ATUALIZAR'}if(error){console.error(error);$('#studentTrackingRows').innerHTML='<tr><td colspan="7"><div class="empty compact">Não foi possível carregar o acompanhamento.</div></td></tr>';return}rows=data||[];render()}
export async function setupAdminAcompanhamento(){await load();$('#trackSearch')?.addEventListener('input',render);$('#trackFilter')?.addEventListener('change',render);$('#refreshStudentTracking')?.addEventListener('click',load);$('#studentTrackingRows')?.addEventListener('click',e=>{const b=e.target.closest('[data-student-detail]');if(b)openDetail(b.dataset.studentDetail)});$('#studentDetailModal')?.addEventListener('click',e=>{if(e.target.id==='studentDetailModal')closeDetail()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#studentDetailModal')?.classList.contains('hidden'))closeDetail()})}
