import {setupAdminMissoes} from './admin_missoes.js';
import {setupAdminQuestoes} from './admin_questoes.js';
import {sb} from './supabase.js';

const $ = (s) => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let disciplines = [], topics = [];

function notice(message, type='success') {
  const el = $('#adminNotice'); if (!el) return;
  el.textContent = message; el.className = `notice ${type}`;
  el.scrollIntoView({behavior:'smooth', block:'nearest'});
  clearTimeout(notice.timer); notice.timer=setTimeout(()=>el.classList.add('hidden'),4500);
}
function setBusy(form,busy){form.querySelectorAll('button,input,select,textarea').forEach(el=>el.disabled=busy)}
function tabs(){const open=name=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('[data-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.panel!==name));history.replaceState(null,'',`#${name}`)};document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>open(btn.dataset.tab)));const wanted=location.hash.slice(1);if(wanted&&document.querySelector(`[data-tab="${wanted}"]`))open(wanted)}
function fillDisciplineSelects(){
  const active=disciplines.filter(d=>d.ativo);
  ['#topicDiscipline','#questionDiscipline'].forEach(sel=>{const el=$(sel);if(!el)return;const current=el.value;el.innerHTML='<option value="">Selecione...</option>'+active.map(d=>`<option value="${d.id}">${esc(d.nome)}</option>`).join('');if(active.some(d=>String(d.id)===current))el.value=current;});
  fillQuestionTopics();
}
function fillQuestionTopics(){const el=$('#questionTopic'),did=Number($('#questionDiscipline')?.value);if(!el)return;el.innerHTML='<option value="">Sem assunto específico</option>'+topics.filter(t=>t.ativo&&t.disciplina_id===did).map(t=>`<option value="${t.id}">${esc(t.nome)}</option>`).join('')}
function renderDisciplines(){const rows=$('#disciplineRows');if(!disciplines.length){rows.innerHTML='<tr><td colspan="4"><div class="empty compact">Nenhuma disciplina cadastrada.</div></td></tr>';return}rows.innerHTML=disciplines.map(d=>`<tr><td>${d.ordem}</td><td><b>${esc(d.nome)}</b></td><td><span class="badge ${d.ativo?'ok':'off'}">${d.ativo?'Ativa':'Inativa'}</span></td><td class="actions"><button class="mini" data-edit-discipline="${d.id}">Editar</button><button class="mini" data-toggle-discipline="${d.id}">${d.ativo?'Desativar':'Ativar'}</button></td></tr>`).join('')}
function renderTopics(){const rows=$('#topicRows');if(!topics.length){rows.innerHTML='<tr><td colspan="4"><div class="empty compact">Nenhum assunto cadastrado.</div></td></tr>';return}const map=Object.fromEntries(disciplines.map(d=>[d.id,d.nome]));rows.innerHTML=topics.map(t=>`<tr><td>${esc(map[t.disciplina_id]||'—')}</td><td><b>${esc(t.nome)}</b></td><td><span class="badge ${t.ativo?'ok':'off'}">${t.ativo?'Ativo':'Inativo'}</span></td><td class="actions"><button class="mini" data-edit-topic="${t.id}">Editar</button><button class="mini" data-toggle-topic="${t.id}">${t.ativo?'Desativar':'Ativar'}</button></td></tr>`).join('')}
async function refresh(){
 const [{data:d,error:de},{data:t,error:te},{count:q,error:qe}]=await Promise.all([sb.from('disciplinas').select('*').order('ordem').order('nome'),sb.from('assuntos').select('*').order('nome'),sb.from('questoes').select('*',{count:'exact',head:true})]);
 if(de||te||qe){notice('Não foi possível carregar os dados. Tente novamente.','error');return}
 disciplines=d||[];topics=t||[];$('#discCount').textContent=disciplines.filter(x=>x.ativo).length;$('#topicCount').textContent=topics.filter(x=>x.ativo).length;$('#questionCount').textContent=q||0;renderDisciplines();renderTopics();fillDisciplineSelects();
}
function resetDiscipline(){const f=$('#disciplineForm');f.reset();f.elements.id.value='';f.elements.ordem.value=0;$('#cancelDiscipline').classList.add('hidden')}
function resetTopic(){const f=$('#topicForm');f.reset();f.elements.id.value='';$('#cancelTopic').classList.add('hidden')}
function bindStructure(){
 $('#disciplineForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,payload={nome:f.elements.nome.value.trim(),ordem:Number(f.elements.ordem.value)||0};if(!payload.nome)return;setBusy(f,true);const r=id?await sb.from('disciplinas').update(payload).eq('id',id):await sb.from('disciplinas').insert(payload);setBusy(f,false);if(r.error)return notice(r.error.message,'error');notice(id?'Disciplina atualizada.':'Disciplina cadastrada.');resetDiscipline();await refresh()});
 $('#topicForm').addEventListener('submit',async e=>{e.preventDefault();const f=e.currentTarget,id=f.elements.id.value,payload={disciplina_id:Number(f.elements.disciplina_id.value),nome:f.elements.nome.value.trim()};if(!payload.disciplina_id||!payload.nome)return;setBusy(f,true);const r=id?await sb.from('assuntos').update(payload).eq('id',id):await sb.from('assuntos').insert(payload);setBusy(f,false);if(r.error)return notice(r.error.message,'error');notice(id?'Assunto atualizado.':'Assunto cadastrado.');resetTopic();await refresh()});
 $('#cancelDiscipline').addEventListener('click',resetDiscipline);$('#cancelTopic').addEventListener('click',resetTopic);
 $('#disciplineRows').addEventListener('click',async e=>{const edit=e.target.dataset.editDiscipline,toggle=e.target.dataset.toggleDiscipline;if(edit){const d=disciplines.find(x=>x.id===Number(edit));const f=$('#disciplineForm');f.elements.id.value=d.id;f.elements.nome.value=d.nome;f.elements.ordem.value=d.ordem;$('#cancelDiscipline').classList.remove('hidden');f.scrollIntoView({behavior:'smooth'})}if(toggle){const d=disciplines.find(x=>x.id===Number(toggle));const {error}=await sb.from('disciplinas').update({ativo:!d.ativo}).eq('id',d.id);if(error)return notice(error.message,'error');notice(`Disciplina ${d.ativo?'desativada':'ativada'}.`);await refresh()}});
 $('#topicRows').addEventListener('click',async e=>{const edit=e.target.dataset.editTopic,toggle=e.target.dataset.toggleTopic;if(edit){const t=topics.find(x=>x.id===Number(edit));const f=$('#topicForm');f.elements.id.value=t.id;f.elements.disciplina_id.value=t.disciplina_id;f.elements.nome.value=t.nome;$('#cancelTopic').classList.remove('hidden');f.scrollIntoView({behavior:'smooth'})}if(toggle){const t=topics.find(x=>x.id===Number(toggle));const {error}=await sb.from('assuntos').update({ativo:!t.ativo}).eq('id',t.id);if(error)return notice(error.message,'error');notice(`Assunto ${t.ativo?'desativado':'ativado'}.`);await refresh()}});
 $('#questionDiscipline').addEventListener('change',fillQuestionTopics);
}
let participants=[];
function statusLabel(s){return {pendente:'Pendente',aprovado:'Ativo',nao_aprovado:'Não aprovado',desativado:'Desativado'}[s]||s}
function renderParticipants(){const rows=$('#participantRows');if(!rows)return;const q=($('#participantSearch')?.value||'').toLowerCase(),filter=$('#participantFilter')?.value||'todos';const list=participants.filter(p=>(filter==='todos'||p.status===filter)&&(`${p.nome||''} ${p.email||''}`.toLowerCase().includes(q)));if(!list.length){rows.innerHTML='<tr><td colspan="4"><div class="empty compact">Nenhum participante encontrado.</div></td></tr>';return}rows.innerHTML=list.map(p=>`<tr><td><div class="participant-cell"><b>${esc(p.nome||'Sem nome')}</b><small>${esc(p.email||'')}</small></div></td><td>${p.created_at?new Date(p.created_at).toLocaleDateString('pt-BR'):'—'}</td><td><span class="badge ${p.status==='aprovado'?'ok':p.status==='pendente'?'wait':'off'}">${statusLabel(p.status)}</span></td><td class="actions participant-actions">${p.status!=='aprovado'?`<button class="mini" data-part-action="aprovar" data-id="${p.id}">Aprovar</button>`:''}${p.status!=='nao_aprovado'?`<button class="mini" data-part-action="nao_aprovado" data-id="${p.id}">Não aprovar</button>`:''}${p.status==='aprovado'?`<button class="mini" data-part-action="desativado" data-id="${p.id}">Desativar</button>`:''}<button class="mini" data-part-action="editar" data-id="${p.id}">Editar</button>${p.id!==window.__adminUserId?`<button class="mini danger-mini" data-part-action="excluir" data-id="${p.id}">Excluir</button>`:''}</td></tr>`).join('')}
async function loadParticipants(){const {data,error}=await sb.from('profiles').select('id,nome,email,role,ativo,status,created_at').order('created_at',{ascending:false});if(error)return notice('Não foi possível carregar os participantes.','error');participants=data||[];renderParticipants()}
function bindParticipants(ctx){window.__adminUserId=ctx.user.id;$('#participantSearch')?.addEventListener('input',renderParticipants);$('#participantFilter')?.addEventListener('change',renderParticipants);$('#participantRows')?.addEventListener('click',async e=>{const b=e.target.closest('[data-part-action]');if(!b)return;const p=participants.find(x=>x.id===b.dataset.id);if(!p)return;const a=b.dataset.partAction;if(a==='editar'){const nome=prompt('Nome do participante:',p.nome||'');if(nome===null)return;const {error}=await sb.rpc('admin_set_participant',{p_user:p.id,p_status:p.status,p_nome:nome});if(error)return notice('Não foi possível editar o participante.','error');notice('Participante atualizado.');return loadParticipants()}if(a==='excluir'){if(!confirm(`Excluir definitivamente o cadastro de ${p.nome||p.email}?`))return;const {error}=await sb.rpc('admin_delete_participant',{p_user:p.id});if(error)return notice('Não foi possível excluir o participante.','error');notice('Cadastro excluído.');return loadParticipants()}const status=a==='aprovar'?'aprovado':a;const {error}=await sb.rpc('admin_set_participant',{p_user:p.id,p_status:status,p_nome:null});if(error)return notice('Não foi possível alterar o acesso.','error');notice(status==='aprovado'?'Participante aprovado.':status==='nao_aprovado'?'Cadastro não aprovado.':'Acesso desativado.');await loadParticipants()})}
export async function setupAdmin(ctx){if(ctx.profile?.role!=='admin'){document.querySelector('#adminArea').innerHTML='<div class="empty">Acesso restrito.</div>';return}tabs();bindStructure();bindParticipants(ctx);await Promise.all([refresh(),loadParticipants(),setupAdminMissoes(ctx)]);await setupAdminQuestoes(ctx,refresh,notice)}
