import {sb} from './supabase.js';

const $=s=>document.querySelector(s);
const esc=(v='')=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let attempts=[];

function fmtDate(v){if(!v)return '—';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleString('pt-BR')}
function fmtScore(v){if(v===null||v===undefined||v==='')return '—';const n=Number(v);return Number.isFinite(n)?`${n.toFixed(1)}%`:'—'}
function statusOf(a){const n=Number(a.violacoes||0);if(a.encerrada_integridade||String(a.finalizada_motivo||'').toLowerCase().includes('segur'))return 'encerrado';if(n>0)return 'advertido';return 'normal'}
function statusBadge(a){const s=statusOf(a);return s==='encerrado'?'<span class="badge off">Encerrado automaticamente</span>':s==='advertido'?'<span class="badge wait">Advertido</span>':'<span class="badge ok">Sem ocorrência</span>'}
function eventLabel(e){const kind=String(e.tipo||e.evento||'').toLowerCase();if(kind.includes('final')||kind.includes('encerr'))return 'Tentativa encerrada';if(Number(e.numero||e.violacao||0)>=2)return '2ª ocorrência — encerramento';if(Number(e.numero||e.violacao||0)===1)return '1ª ocorrência — advertência';return e.descricao||'Saída da tela registrada'}

function fillSimulations(){const sel=$('#integritySimulation');if(!sel)return;const current=sel.value;const sims=[...new Map(attempts.map(a=>[String(a.simulado_id),a.simulado_titulo||'Simulado'])).entries()].sort((a,b)=>a[1].localeCompare(b[1],'pt-BR'));sel.innerHTML='<option value="">Todos os simulados</option>'+sims.map(([id,t])=>`<option value="${esc(id)}">${esc(t)}</option>`).join('');if(sims.some(([id])=>id===current))sel.value=current}
function updateSummary(){const warned=attempts.filter(a=>Number(a.violacoes||0)>0).length;const closed=attempts.filter(a=>statusOf(a)==='encerrado').length;$('#integrityAttempts').textContent=attempts.length;$('#integrityWarnings').textContent=warned;$('#integrityAutoClosed').textContent=closed;$('#integrityEvents').textContent=attempts.reduce((s,a)=>s+Number(a.violacoes||0),0)}
function filtered(){const q=($('#integritySearch')?.value||'').trim().toLowerCase(),sim=$('#integritySimulation')?.value||'',st=$('#integrityStatus')?.value||'todos';return attempts.filter(a=>(!q||`${a.aluno_nome||''} ${a.aluno_email||''} ${a.simulado_titulo||''}`.toLowerCase().includes(q))&&(!sim||String(a.simulado_id)===sim)&&(st==='todos'||statusOf(a)===st))}
function render(){const rows=$('#integrityRows');if(!rows)return;const list=filtered();if(!list.length){rows.innerHTML='<tr><td colspan="8"><div class="empty compact">Nenhuma tentativa encontrada com esses filtros.</div></td></tr>';return}rows.innerHTML=list.map(a=>`<tr class="integrity-row ${statusOf(a)==='encerrado'?'integrity-critical':''}"><td><div class="participant-cell"><b>${esc(a.aluno_nome||'Aluno')}</b><small>${esc(a.aluno_email||'')}</small></div></td><td><b>${esc(a.simulado_titulo||'—')}</b><small class="table-sub">Tentativa ${esc(a.numero_tentativa||1)}</small></td><td>${fmtDate(a.iniciada_em)}</td><td>${Number(a.respondidas||0)}${a.total_questoes?` / ${Number(a.total_questoes)}`:''}</td><td><span class="integrity-count ${Number(a.violacoes||0)>0?'has-events':''}">${Number(a.violacoes||0)}</span></td><td>${statusBadge(a)}</td><td>${fmtScore(a.pontuacao)}</td><td><button class="mini" data-integrity-detail="${a.tentativa_id}">Detalhes</button></td></tr>`).join('')}
function showDetail(id){const a=attempts.find(x=>Number(x.tentativa_id)===Number(id)),box=$('#integrityDetail');if(!a||!box)return;const events=Array.isArray(a.eventos)?a.eventos:[];const timeline=events.length?events.map((e,i)=>`<div class="integrity-event"><div class="integrity-event-dot">${i+1}</div><div><b>${esc(eventLabel(e))}</b><small>${fmtDate(e.registrada_em||e.created_at||e.data)}</small>${e.detalhe?`<p>${esc(e.detalhe)}</p>`:''}</div></div>`).join(''):'<div class="empty compact">Nenhuma ocorrência registrada nesta tentativa.</div>';box.innerHTML=`<div class="section-title compact-title"><div><span class="eyebrow">TENTATIVA #${esc(a.tentativa_id)}</span><h3>${esc(a.aluno_nome||'Aluno')} · ${esc(a.simulado_titulo||'Simulado')}</h3></div><button class="mini" id="closeIntegrityDetail" type="button">FECHAR</button></div><div class="integrity-detail-grid"><div><small>Início</small><b>${fmtDate(a.iniciada_em)}</b></div><div><small>Finalização</small><b>${fmtDate(a.finalizada_em)}</b></div><div><small>Respondidas</small><b>${Number(a.respondidas||0)}${a.total_questoes?` / ${Number(a.total_questoes)}`:''}</b></div><div><small>Ocorrências</small><b>${Number(a.violacoes||0)}</b></div><div><small>Resultado</small><b>${fmtScore(a.pontuacao)}</b></div><div><small>Situação</small><b>${statusOf(a)==='encerrado'?'Encerramento automático':statusOf(a)==='advertido'?'Advertência registrada':'Conclusão normal'}</b></div></div>${a.finalizada_motivo?`<div class="integrity-reason"><small>Motivo de finalização</small><p>${esc(a.finalizada_motivo_legivel||'Finalização registrada pela plataforma.')}</p></div>`:''}<div class="section-title compact-title"><h3>Linha do tempo</h3></div><div class="integrity-timeline">${timeline}</div>`;box.classList.remove('hidden');box.scrollIntoView({behavior:'smooth',block:'start'});$('#closeIntegrityDetail')?.addEventListener('click',()=>box.classList.add('hidden'),{once:true})}

async function load(notice){const btn=$('#refreshIntegrity');if(btn){btn.disabled=true;btn.textContent='ATUALIZANDO...'}const {data,error}=await sb.rpc('admin_integridade_simulados');if(btn){btn.disabled=false;btn.textContent='ATUALIZAR'}if(error){console.error(error);attempts=[];updateSummary();render();return notice('Não foi possível carregar a auditoria dos simulados. Execute o SQL da V2.2 no banco e tente novamente.','error')}attempts=Array.isArray(data)?data:(data?.tentativas||[]);attempts.sort((a,b)=>new Date(b.iniciada_em||0)-new Date(a.iniciada_em||0));updateSummary();fillSimulations();render()}

export async function setupAdminIntegridade(ctx,notice){if(ctx?.profile?.role!=='admin')return;$('#integritySearch')?.addEventListener('input',render);$('#integritySimulation')?.addEventListener('change',render);$('#integrityStatus')?.addEventListener('change',render);$('#refreshIntegrity')?.addEventListener('click',()=>load(notice));$('#integrityRows')?.addEventListener('click',e=>{const b=e.target.closest('[data-integrity-detail]');if(b)showDetail(b.dataset.integrityDetail)});await load(notice)}
