import {requireAuth,getProfile,signOut,avatarUrl} from './auth.js';
import {mountNotifications} from './notifications.js';

const labels={dashboard:'Início',missao:'Minha Missão',cronograma:'Cronograma',calendario:'Calendário',plano:'Plano do dia',teoria:'Teoria Direcionada',revisao:'Revisar hoje',questoes:'Questões',flashcards:'Flashcards',erros:'Caderno de Erros',simulados:'Simulados',desempenho:'Desempenho',ranking:'Ranking',objetivos:'Meu objetivo',ciclo:'Ciclo de estudo',semana:'Minha semana',sessao:'Sessão de estudo',retafinal:'Reta final',admin:'Administração',perfil:'Meu perfil'};
const report=(where,error)=>console.error(`[Foco na Missão] ${where}:`,error);
function initials(name=''){return name.trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'FM'}
function formatNow(date=new Date()){const d=new Intl.DateTimeFormat('pt-BR',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(date);const t=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(date);return `${d}, ${t}`}
function mountDateTime(container){const clock=document.createElement('time');clock.className='header-datetime';clock.setAttribute('aria-label','Data e hora atuais');const update=()=>{const now=new Date();clock.dateTime=now.toISOString();clock.textContent=formatNow(now)};update();const timer=setInterval(update,1000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});container.appendChild(clock)}
function mountAccount(profile,container){const wrap=document.createElement('div');wrap.className='account-wrap';const img=profile.avatar_path?`<img src="${avatarUrl(profile.avatar_path)}?v=${Date.now()}" alt="Foto de ${profile.nome||'participante'}">`:`<span>${initials(profile.nome)}</span>`;wrap.innerHTML=`<div class="account-avatar">${img}</div><b class="account-name">${profile.nome||'Participante'}</b><button class="account-gear" type="button" aria-label="Opções da conta" aria-expanded="false">⚙</button><div class="account-menu hidden"><a href="${profile.role==='admin'?'./admin.html#perfil':'./perfil.html'}">👤 Editar perfil</a><button type="button" class="logout-menu">🚪 Sair</button></div>`;container.appendChild(wrap);const gear=wrap.querySelector('.account-gear'),menu=wrap.querySelector('.account-menu');if(gear&&menu){gear.addEventListener('click',()=>{const opening=menu.classList.contains('hidden');menu.classList.toggle('hidden');gear.setAttribute('aria-expanded',String(opening))});wrap.querySelector('.logout-menu')?.addEventListener('click',signOut);document.addEventListener('click',e=>{if(!wrap.contains(e.target)){menu.classList.add('hidden');gear.setAttribute('aria-expanded','false')}})}}
function mountHeader(profile,ctx){const top=document.querySelector('.topbar');if(!top)return;top.querySelectorAll('.toolbar,#userName,.avatar,.account-wrap,.topbar-right,.header-datetime,.notif-wrap').forEach(el=>el.remove());const right=document.createElement('div');right.className='topbar-right';try{mountDateTime(right)}catch(e){report('relógio',e)}try{mountAccount(profile,right)}catch(e){report('conta',e)}top.appendChild(right);Promise.resolve(mountNotifications(ctx,right)).catch(e=>report('notificações',e))}
function mountMobileNav(page){if(document.querySelector('.mobile-bottom-nav'))return;const nav=document.createElement('nav');nav.className='mobile-bottom-nav';nav.setAttribute('aria-label','Navegação principal');nav.innerHTML=`<a href="./index.html" class="${page==='dashboard'?'active':''}"><span>🏠</span><small>Início</small></a><a href="./missao.html" class="${page==='missao'?'active':''}"><span>🎯</span><small>Missão</small></a><a href="./questoes.html" class="${page==='questoes'?'active':''}"><span>📝</span><small>Questões</small></a><a href="./flashcards.html" class="${page==='flashcards'?'active':''}"><span>🧠</span><small>Cards</small></a><button type="button" data-more><span>☰</span><small>Mais</small></button>`;document.body.appendChild(nav);nav.querySelector('[data-more]')?.addEventListener('click',()=>{document.querySelector('.sidebar')?.classList.add('open');document.querySelector('.overlay')?.classList.add('open')})}
export async function boot(page){const user=await requireAuth();if(!user)return null;const profile=await getProfile(user);if(!profile){document.body.innerHTML='<main class="login-shell"><section class="login-card"><h1>Cadastro não encontrado</h1><p>Não foi possível carregar seu cadastro.</p><a class="btn" href="./login.html">VOLTAR</a></section></main>';return null}if(profile.status!=='aprovado'||!profile.ativo){await signOut();return null}
  document.querySelector('#pageTitle')?.replaceChildren(document.createTextNode(labels[page]||'Foco na Missão'));
  document.querySelector(`[data-nav="${page}"]`)?.classList.add('active');
  if(profile.role==='admin')document.querySelectorAll('[data-admin]').forEach(el=>el.classList.remove('hidden'));else if(page==='admin'){location.href='./index.html';return null}
  const ctx={user,profile};
  try{mountHeader(profile,ctx)}catch(e){report('cabeçalho',e)}
  try{mountMobileNav(page)}catch(e){report('menu móvel',e)}
  try{document.querySelector('#logout')?.addEventListener('click',signOut)}catch(e){report('logout',e)}
  try{const side=document.querySelector('.sidebar'),overlay=document.querySelector('.overlay');document.querySelector('#mobileMenu')?.addEventListener('click',()=>{side?.classList.toggle('open');overlay?.classList.toggle('open')});overlay?.addEventListener('click',()=>{side?.classList.remove('open');overlay?.classList.remove('open')})}catch(e){report('menu lateral',e)}
  return ctx
}
function markLoadFailure(page,error){report(`Falha em ${page}`,error);document.querySelectorAll('.empty,.loading').forEach(el=>{if(/carregando|preparando|buscando|analisando/i.test(el.textContent||''))el.textContent='Não foi possível carregar estes dados.'});const main=document.querySelector('.main');if(main&&!document.querySelector('#pageLoadError')){const box=document.createElement('div');box.id='pageLoadError';box.className='notice error';box.style.margin='16px 0';box.textContent='Uma parte desta página encontrou um erro. Os demais recursos continuam disponíveis.';main.prepend(box)}}
export async function runPage(page,loader){let ctx=null;try{ctx=await boot(page)}catch(error){markLoadFailure(`${page}/inicialização`,error);window.__FM_PAGE_READY=true;return null}if(!ctx){window.__FM_PAGE_READY=true;return null}window.__FM_PAGE_LOADER_STARTED=true;try{await loader(ctx);window.__FM_PAGE_READY=true;return ctx}catch(error){markLoadFailure(`${page}/conteúdo`,error);window.__FM_PAGE_READY=true;return ctx}}
