import {sb} from './supabase.js';
const $=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
let month=new Date();month.setDate(1);let allDays=new Map();
function add(day,type,count=1,extra={}){if(!day)return;const x=allDays.get(day)||{q:0,cards:0,missions:0,sims:0,minutes:0,details:[]};x[type]=(x[type]||0)+count;x.details.push({...extra,type});allDays.set(day,x)}
function activityScore(x){return (x.q||0)+(x.cards||0)*.5+(x.missions||0)*10+(x.sims||0)*25}
function streaks(){const days=[...allDays.keys()].filter(k=>activityScore(allDays.get(k))>0).sort();const set=new Set(days);let cur=new Date();cur.setHours(12,0,0,0);if(!set.has(iso(cur)))cur.setDate(cur.getDate()-1);let current=0;while(set.has(iso(cur))){current++;cur.setDate(cur.getDate()-1)}let best=0,run=0,prev=null;for(const k of days){const d=new Date(`${k}T12:00:00`);if(prev){const diff=Math.round((d-prev)/86400000);run=diff===1?run+1:1}else run=1;best=Math.max(best,run);prev=d}return{current,best}}
function renderDetail(day){const x=allDays.get(day);const host=$('#calendarDetail');if(!x){host.innerHTML=`<div class="empty">Nenhuma atividade registrada em ${new Date(day+'T12:00:00').toLocaleDateString('pt-BR')}.</div>`;return}host.innerHTML=`<div class="section-title"><div><span class="eyebrow">${new Date(day+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long'})}</span><h2>${new Date(day+'T12:00:00').toLocaleDateString('pt-BR')}</h2></div></div><div class="grid stats calendar-day-stats"><div class="stat"><span>📝 Questões</span><b>${x.q||0}</b></div><div class="stat"><span>🧠 Flashcards</span><b>${x.cards||0}</b></div><div class="stat"><span>🎯 Missões</span><b>${x.missions||0}</b></div><div class="stat"><span>🏆 Simulados</span><b>${x.sims||0}</b></div></div>`}
function render(){const y=month.getFullYear(),m=month.getMonth();$('#calMonthTitle').textContent=month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'});const first=new Date(y,m,1),last=new Date(y,m+1,0);const cells=[];for(let i=0;i<first.getDay();i++)cells.push('<div class="calendar-cell blank"></div>');for(let d=1;d<=last.getDate();d++){const dt=new Date(y,m,d),key=iso(dt),x=allDays.get(key),score=x?activityScore(x):0;const level=score>=60?4:score>=30?3:score>=10?2:score>0?1:0;cells.push(`<button class="calendar-cell ${level?'heat-'+level:''} ${key===iso(new Date())?'today':''}" data-day="${key}"><b>${d}</b>${x?`<small>${x.q||0}q · ${x.cards||0}c</small>`:'<small>—</small>'}</button>`)}$('#calendarGrid').innerHTML=cells.join('');document.querySelectorAll('[data-day]').forEach(b=>b.addEventListener('click',()=>renderDetail(b.dataset.day)));const s=streaks();$('#calCurrentStreak').textContent=`${s.current} dia${s.current===1?'':'s'}`;$('#calBestStreak').textContent=`${s.best} dia${s.best===1?'':'s'}`}
export async function loadCalendar(ctx){const uid=ctx.user.id;const [{data:r},{data:f},{data:a},{data:s}]=await Promise.all([sb.from('respostas').select('created_at,tempo_segundos').eq('user_id',uid),sb.from('flashcard_revisoes').select('reviewed_at').eq('user_id',uid),sb.from('atividade_progresso').select('data,concluida').eq('user_id',uid).eq('concluida',true),sb.from('simulado_tentativas').select('finalizada_em,tempo_segundos,status').eq('user_id',uid).eq('status','finalizada')]);for(const x of r||[])add(iso(new Date(x.created_at)),'q',1,{label:'Questão'});for(const x of f||[])add(iso(new Date(x.reviewed_at)),'cards',1,{label:'Flashcard'});for(const x of a||[])add(String(x.data).slice(0,10),'missions',1,{label:'Missão'});for(const x of s||[])if(x.finalizada_em)add(iso(new Date(x.finalizada_em)),'sims',1,{label:'Simulado'});render();$('#calPrev').onclick=()=>{month.setMonth(month.getMonth()-1);render()};$('#calNext').onclick=()=>{month.setMonth(month.getMonth()+1);render()}}
