import {sb} from './supabase.js';
const $=s=>document.querySelector(s),esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let ctx,ciclo,blocos=[],disc=[],assuntos=[];
function msg(t,e=false){const x=$('#cycleNotice');x.textContent=t;x.className=`notice ${e?'error':'success'}`;x.classList.remove('hidden');setTimeout(()=>x.classList.add('hidden'),3000)}
async function refresh(){
 const {data:c}=await sb.from('estudo_ciclos').select('*').eq('user_id',ctx.user.id).eq('ativo',true).maybeSingle();ciclo=c||null;
 if(ciclo){const {data:b}=await sb.from('estudo_ciclo_blocos').select('*,disciplinas(nome),assuntos(nome)').eq('ciclo_id',ciclo.id).order('ordem');blocos=b||[]}else blocos=[];
 let next=null;if(blocos.length){const ids=blocos.map(x=>x.id),{data:e}=await sb.from('sessoes_estudo').select('ciclo_bloco_id,finalizada_em').eq('user_id',ctx.user.id).in('ciclo_bloco_id',ids).order('finalizada_em',{ascending:false}).limit(1);const last=e?.[0]?.ciclo_bloco_id,idx=blocos.findIndex(x=>Number(x.id)===Number(last));next=blocos[(idx+1+blocos.length)%blocos.length]}
 $('#cycleSummary').innerHTML=ciclo?`<div><span class="eyebrow">CICLO ATIVO</span><h2>${esc(ciclo.titulo)}</h2><p>${blocos.length} blocos configurados. O ciclo continua de onde você parou.</p></div>${next?`<a class="btn" href="./sessao.html?ciclo_bloco=${next.id}">INICIAR PRÓXIMO · ${esc(next.disciplinas?.nome||'DISCIPLINA')}</a>`:''}`:`<div><h2>Crie seu primeiro ciclo</h2><p class="muted">Monte uma sequência que se repete independentemente do dia da semana.</p></div>`;
 $('#cycleList').innerHTML=blocos.length?blocos.map((b,i)=>`<article class="card cycle-block"><span class="cycle-order">${i+1}</span><div><b>${esc(b.disciplinas?.nome||'Disciplina')}</b><small>${esc(b.assuntos?.nome||'Conteúdo geral')} · ${b.tipo} · ${b.minutos_planejados} min</small></div><div class="actions"><a class="btn secondary mini-btn" href="./sessao.html?ciclo_bloco=${b.id}">ESTUDAR</a><button class="btn ghost mini-btn" data-del="${b.id}">REMOVER</button></div></article>`).join(''):'<div class="card empty">Nenhum bloco configurado.</div>';
 $('#cycleCreate').classList.toggle('hidden',!!ciclo);$('#cycleAdd').classList.toggle('hidden',!ciclo);
}
export async function loadCycle(c){ctx=c;const [{data:d},{data:a}]=await Promise.all([sb.from('disciplinas').select('id,nome').order('nome'),sb.from('assuntos').select('id,nome,disciplina_id').order('nome')]);disc=d||[];assuntos=a||[];
 const fill=()=>{$('#blockDiscipline').innerHTML='<option value="">Disciplina</option>'+disc.map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('');$('#blockSubject').innerHTML='<option value="">Conteúdo geral</option>'};fill();
 $('#blockDiscipline').onchange=()=>{$('#blockSubject').innerHTML='<option value="">Conteúdo geral</option>'+assuntos.filter(x=>Number(x.disciplina_id)===Number($('#blockDiscipline').value)).map(x=>`<option value="${x.id}">${esc(x.nome)}</option>`).join('')};
 $('#createCycleForm').onsubmit=async e=>{e.preventDefault();const fd=new FormData(e.target);const {data:u}=await sb.from('usuario_objetivo').select('objetivo_id').eq('user_id',ctx.user.id).maybeSingle();const {error}=await sb.from('estudo_ciclos').insert({user_id:ctx.user.id,objetivo_id:u?.objetivo_id||null,titulo:fd.get('titulo')||'Meu ciclo'});if(error)return msg('Não foi possível criar o ciclo.',true);e.target.reset();await refresh()};
 $('#addBlockForm').onsubmit=async e=>{e.preventDefault();if(!ciclo)return;const fd=new FormData(e.target),ordem=blocos.length+1;const {error}=await sb.from('estudo_ciclo_blocos').insert({ciclo_id:ciclo.id,disciplina_id:Number(fd.get('disciplina_id')),assunto_id:fd.get('assunto_id')?Number(fd.get('assunto_id')):null,tipo:fd.get('tipo'),minutos_planejados:Number(fd.get('minutos')),ordem});if(error)return msg('Não foi possível adicionar o bloco.',true);e.target.reset();fill();await refresh()};
 $('#cycleList').onclick=async e=>{const b=e.target.closest('[data-del]');if(!b)return;await sb.from('estudo_ciclo_blocos').delete().eq('id',b.dataset.del);await refresh()};
 await refresh();}
