import {sb} from './supabase.js';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let ctx=null,objectives=[],current=null;
function notice(m,t='success'){const e=$('#objectiveNotice');if(!e)return;e.textContent=m;e.className=`notice ${t}`;e.classList.remove('hidden');clearTimeout(notice.t);notice.t=setTimeout(()=>e.classList.add('hidden'),3500)}
function card(o){const on=Number(current)===Number(o.id);return `<article class="card objective-card ${on?'active':''}"><div><span class="badge ${on?'ok':''}">${on?'ATUAL':'DISPONÍVEL'}</span><h3>${esc(o.titulo)}</h3><p>${esc(o.descricao||'')}</p><small>${[o.orgao,o.banca,o.ano].filter(Boolean).map(esc).join(' · ')}</small>${o.data_prova?`<small>📅 Prova: ${new Date(`${o.data_prova}T12:00:00`).toLocaleDateString('pt-BR')}</small>`:''}</div><button class="btn ${on?'secondary':''}" data-objective="${o.id}" type="button">${on?'SELECIONADO':'USAR ESTE OBJETIVO'}</button></article>`}
function statusLabel(s){return s==='estudado'?'Estudado':s==='estudando'?'Em estudo':'Não iniciado'}
function statusClass(s){return s==='estudado'?'ok':s==='estudando'?'warn':'off'}
async function detail(id){
  const obj=objectives.find(x=>Number(x.id)===Number(id));
  const [{data:d},{data:a},{data:r},{data:p}]=await Promise.all([
    sb.from('objetivo_disciplinas').select('disciplina_id,peso,ordem,disciplinas(id,nome)').eq('objetivo_id',id).order('ordem'),
    sb.from('objetivo_assuntos').select('assunto_id,prioridade,assuntos(id,nome,disciplina_id,disciplinas(nome))').eq('objetivo_id',id),
    sb.from('respostas').select('acertou,questoes(disciplina_id,assunto_id)').eq('user_id',ctx.user.id),
    sb.from('usuario_objetivo_assuntos').select('assunto_id,status,estudado_em,updated_at').eq('user_id',ctx.user.id).eq('objetivo_id',id)
  ]);
  const topicIds=(a||[]).map(x=>Number(x.assunto_id));
  let sub=[];
  if(topicIds.length){const {data}=await sb.from('questoes').select('assunto_id,subassunto').in('assunto_id',topicIds).not('subassunto','is',null);sub=data||[]}
  const responses=r||[],progress=new Map((p||[]).map(x=>[Number(x.assunto_id),x]));
  const disc=(d||[]).map(x=>{const rr=responses.filter(z=>Number(z.questoes?.disciplina_id)===Number(x.disciplina_id)),h=rr.filter(z=>z.acertou).length,dt=(a||[]).filter(t=>Number(t.assuntos?.disciplina_id)===Number(x.disciplina_id)),studied=dt.filter(t=>progress.get(Number(t.assunto_id))?.status==='estudado').length;return {...x,total:rr.length,hits:h,acc:rr.length?Math.round(h/rr.length*100):0,topicTotal:dt.length,topicStudied:studied,coverage:dt.length?Math.round(studied/dt.length*100):0}});
  const topics=(a||[]).map(x=>{const rr=responses.filter(z=>Number(z.questoes?.assunto_id)===Number(x.assunto_id)),h=rr.filter(z=>z.acertou).length,pr=progress.get(Number(x.assunto_id)),subs=[...new Set(sub.filter(s=>Number(s.assunto_id)===Number(x.assunto_id)).map(s=>String(s.subassunto||'').trim()).filter(Boolean))];return {...x,total:rr.length,hits:h,acc:rr.length?Math.round(h/rr.length*100):0,status:pr?.status||(rr.length?'estudando':'nao_iniciado'),subs}});
  const covered=topics.filter(x=>x.status==='estudado').length,started=topics.filter(x=>x.status!=='nao_iniciado'||x.total>0).length,coverage=topics.length?Math.round(covered/topics.length*100):0;
  const docs=[];
  if(obj?.edital_pdf_path){const {data}=await sb.storage.from('editais').createSignedUrl(obj.edital_pdf_path,300);if(data?.signedUrl)docs.push(`<a class="btn secondary" target="_blank" rel="noopener" href="${data.signedUrl}">VER EDITAL OFICIAL</a>`)}
  if(obj?.edital_verticalizado_path){const {data}=await sb.storage.from('editais').createSignedUrl(obj.edital_verticalizado_path,300);if(data?.signedUrl)docs.push(`<a class="btn secondary" target="_blank" rel="noopener" href="${data.signedUrl}">VER VERTICALIZADO</a>`)}
  const weighted=disc.reduce((sum,x)=>sum+x.coverage*Number(x.peso||1),0),weights=disc.reduce((sum,x)=>sum+Number(x.peso||1),0),weightedCoverage=weights?Math.round(weighted/weights):coverage;
  $('#objectiveDetail').innerHTML=`
  <section class="card objective-coverage-hero"><div><span class="eyebrow">EDITAL VERTICALIZADO</span><h2>${weightedCoverage}% do edital coberto</h2><p>${covered} de ${topics.length} assuntos marcados como estudados · ${started} já iniciados.</p>${docs.length?`<div class="objective-doc-links">${docs.join('')}</div>`:''}</div><div class="coverage-ring"><strong>${weightedCoverage}%</strong><small>cobertura</small></div></section>
  <div class="progress objective-main-progress"><i style="width:${weightedCoverage}%"></i></div>
  <div class="section-title"><div><h2>Disciplinas do edital</h2><span class="muted">Cobertura por conteúdo e desempenho em questões.</span></div></div>
  <div class="objective-discipline-list">${disc.map(x=>`<div class="objective-discipline card compact-card"><div><b>${esc(x.disciplinas?.nome||'Disciplina')}</b><small>Peso ${Number(x.peso||1).toFixed(1)} · ${x.topicStudied}/${x.topicTotal} assuntos estudados</small></div><div><div class="objective-dual-metric"><span>Cobertura <b>${x.coverage}%</b></span><span>Questões <b>${x.total?`${x.acc}%`:'—'}</b></span></div><div class="progress"><i style="width:${x.coverage}%"></i></div><a class="text-link" href="./questoes.html?disciplina=${x.disciplina_id}&quantidade=20">Praticar disciplina →</a></div></div>`).join('')||'<div class="empty compact">Nenhuma disciplina configurada.</div>'}</div>
  ${topics.length?`<div class="section-title objective-topics-title"><div><h3>Conteúdo verticalizado</h3><span class="muted">Marque seu avanço e acompanhe o que ainda falta cobrir.</span></div></div><div class="verticalized-list">${disc.map(dd=>{const arr=topics.filter(t=>Number(t.assuntos?.disciplina_id)===Number(dd.disciplina_id)).sort((x,y)=>Number(y.prioridade)-Number(x.prioridade)||x.assuntos.nome.localeCompare(y.assuntos.nome));if(!arr.length)return '';return `<details class="verticalized-discipline" open><summary><span>${esc(dd.disciplinas?.nome||'Disciplina')}</span><small>${arr.filter(x=>x.status==='estudado').length}/${arr.length} estudados</small></summary><div class="verticalized-topics">${arr.map(t=>`<article class="verticalized-topic"><div class="verticalized-topic-main"><span class="badge ${statusClass(t.status)}">${statusLabel(t.status)}</span><div><b>${esc(t.assuntos?.nome||'Assunto')}</b><small>Incidência ${t.prioridade}/5 · ${t.total} questões${t.total?` · ${t.acc}% de acerto`:''}</small></div></div><div class="verticalized-topic-actions"><select data-topic-status="${t.assunto_id}"><option value="nao_iniciado" ${t.status==='nao_iniciado'?'selected':''}>Não iniciado</option><option value="estudando" ${t.status==='estudando'?'selected':''}>Em estudo</option><option value="estudado" ${t.status==='estudado'?'selected':''}>Estudado</option></select><a class="mini" href="./questoes.html?assunto=${t.assunto_id}&quantidade=10">PRATICAR</a></div>${t.subs.length?`<details class="subtopic-list"><summary>Subassuntos encontrados (${t.subs.length})</summary><div>${t.subs.map(s=>`<span>${esc(s)}</span>`).join('')}</div></details>`:''}</article>`).join('')}</div></details>`}).join('')}</div>`:''}`;
  $('#objectiveDetail').querySelectorAll('[data-topic-status]').forEach(sel=>sel.onchange=async()=>{const status=sel.value,payload={user_id:ctx.user.id,objetivo_id:Number(id),assunto_id:Number(sel.dataset.topicStatus),status,updated_at:new Date().toISOString(),estudado_em:status==='estudado'?new Date().toISOString():null};const {error}=await sb.from('usuario_objetivo_assuntos').upsert(payload,{onConflict:'user_id,objetivo_id,assunto_id'});if(error)return notice('Não foi possível atualizar o progresso.','error');notice('Cobertura do edital atualizada.');await detail(id)})
}
export async function loadObjectives(c){ctx=c;const [{data:o,error},{data:u}]=await Promise.all([sb.from('concursos_objetivos').select('*').eq('ativo',true).order('titulo'),sb.from('usuario_objetivo').select('objetivo_id').eq('user_id',ctx.user.id).maybeSingle()]);if(error){$('#objectiveCards').innerHTML='<div class="card empty">Estrutura de objetivos ainda não está disponível.</div>';return}objectives=o||[];current=u?.objetivo_id||null;const render=()=>{$('#objectiveCards').innerHTML=objectives.length?objectives.map(card).join(''):'<div class="card empty">Nenhum objetivo publicado.</div>'};render();if(current)await detail(current);$('#objectiveCards').onclick=async e=>{const b=e.target.closest('[data-objective]');if(!b)return;const id=Number(b.dataset.objective);const {error}=await sb.from('usuario_objetivo').upsert({user_id:ctx.user.id,objetivo_id:id},{onConflict:'user_id'});if(error)return notice('Não foi possível alterar o objetivo.','error');current=id;render();await detail(id);notice('Objetivo atualizado.')}}
