import {sb} from './supabase.js';
const $=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
function item(i,x){return `<article class="card plan-item ${x.primary?'primary':''}"><div class="plan-order">${i+1}</div><div class="plan-icon">${x.icon}</div><div><span class="eyebrow">${esc(x.kind)}</span><h3>${esc(x.title)}</h3><p>${esc(x.desc)}</p><small>${esc(x.meta||'')}</small></div><a class="btn ${x.primary?'':'secondary'}" href="${x.href}">${x.cta||'ABRIR'}</a></article>`}
export async function loadPlan(ctx){const uid=ctx.user.id;const render=async()=>{try{$('#planStatus').textContent='ATUALIZANDO';const d=today();const [{data:acts},{data:prog},{data:errs},{data:cards},{data:revs},{data:resp},{data:running},{data:obj}]=await Promise.all([
sb.from('atividades').select('id,titulo,tipo,meta_quantidade,meta_minutos,ordem,cronogramas(ativo)').eq('data',d).eq('ativo',true).order('ordem'),
sb.from('atividade_progresso').select('atividade_id,concluida').eq('user_id',uid).eq('data',d),
sb.from('caderno_erros').select('questao_id,erros,dominado,questoes(assunto_id,disciplina_id,assuntos(nome),disciplinas(nome))').eq('user_id',uid),
sb.from('flashcards').select('id').eq('ativo',true),
sb.from('flashcard_revisoes').select('flashcard_id,proxima_revisao,reviewed_at').eq('user_id',uid).order('reviewed_at',{ascending:false}),
sb.from('respostas').select('acertou,questoes(assunto_id,disciplina_id,assuntos(nome),disciplinas(nome))').eq('user_id',uid),
sb.from('simulado_tentativas').select('id,status,simulados(titulo)').eq('user_id',uid).eq('status','em_andamento').order('iniciada_em',{ascending:false}).limit(1).maybeSingle(),
sb.from('usuario_objetivo').select('objetivo_id,concursos_objetivos(titulo)').eq('user_id',uid).maybeSingle()
]);
const pm=new Map((prog||[]).map(x=>[Number(x.atividade_id),!!x.concluida]));const mission=(acts||[]).filter(a=>a.cronogramas?.ativo!==false&&!pm.get(Number(a.id)));const latest=new Map();for(const r of revs||[])if(!latest.has(Number(r.flashcard_id)))latest.set(Number(r.flashcard_id),r);const due=(cards||[]).filter(c=>{const r=latest.get(Number(c.id));return !r||!r.proxima_revisao||r.proxima_revisao<=d}).length;const recurring=(errs||[]).filter(e=>!e.dominado&&Number(e.erros)>=2).sort((a,b)=>Number(b.erros)-Number(a.erros));const map=new Map();for(const r of resp||[]){const q=r.questoes;if(!q?.assunto_id)continue;const k=Number(q.assunto_id),x=map.get(k)||{id:k,disciplineId:Number(q.disciplina_id)||null,name:q.assuntos?.nome||'Assunto',disc:q.disciplinas?.nome||'',n:0,h:0};x.n++;if(r.acertou)x.h++;map.set(k,x)}const weak=[...map.values()].filter(x=>x.n>=3).map(x=>({...x,acc:Math.round(x.h/x.n*100)})).filter(x=>x.acc<70).sort((a,b)=>a.acc-b.acc||b.n-a.n);
let allowedDisc=null;if(obj?.objetivo_id){const {data:od}=await sb.from('objetivo_disciplinas').select('disciplina_id').eq('objetivo_id',obj.objetivo_id);allowedDisc=new Set((od||[]).map(x=>Number(x.disciplina_id)));if(allowedDisc.size)weak.splice(0,weak.length,...weak.filter(x=>!x.disciplineId||allowedDisc.has(Number(x.disciplineId))))}
const items=[];if(running)items.push({icon:'🏆',kind:'Retomada',title:'Continuar simulado em andamento',desc:running.simulados?.titulo||'Você possui uma tentativa em andamento.',meta:'Prioridade máxima enquanto a tentativa estiver aberta.',href:`./simulados.html?tentativa=${running.id}`,cta:'CONTINUAR',minutes:30});for(const a of mission.slice(0,2))items.push({icon:'🎯',kind:'Missão do dia',title:a.titulo,desc:'Atividade publicada para a missão de hoje.',meta:a.meta_minutos?`${a.meta_minutos} min`:a.meta_quantidade?`${a.meta_quantidade} itens`:'Atividade programada',href:'./missao.html',minutes:Number(a.meta_minutos)||15});if(recurring.length)items.push({icon:'⚠️',kind:'Correção',title:'Refazer erros recorrentes',desc:'Volte às questões que continuam aparecendo no seu Caderno de Erros.',meta:`${recurring.length} pendência${recurring.length===1?'':'s'}`,href:`./questoes.html?modo=erros&quantidade=${Math.min(15,Math.max(5,recurring.length))}`,minutes:20});if(due)items.push({icon:'🧠',kind:'Revisão',title:'Revisar flashcards vencidos',desc:'Feche a rodada dos cartões previstos para hoje.',meta:`${due} flashcard${due===1?'':'s'}`,href:'./flashcards.html',minutes:Math.min(25,Math.max(10,Math.ceil(due/3)))});if(weak.length){const w=weak[0];items.push({icon:'📉',kind:'Reforço',title:`Praticar ${w.name}`,desc:'Sessão curta no assunto com menor aproveitamento consolidado.',meta:`${w.disc} · ${w.acc}% em ${w.n} respostas`,href:`./questoes.html?assunto=${w.id}&quantidade=10`,minutes:20})}if(!items.length)items.push({icon:'✅',kind:'Livre',title:'Rotina em dia',desc:'Não há pendência prioritária. Avance no banco de questões ou antecipe conteúdo da missão.',meta:'Constância também é saber quando avançar.',href:'./questoes.html?quantidade=20',minutes:30});items.forEach((x,i)=>x.primary=i===0);$('#planList').innerHTML=items.slice(0,5).map(item).join('');$('#planSteps').textContent=Math.min(5,items.length);$('#planMinutes').textContent=`${items.slice(0,5).reduce((a,x)=>a+(x.minutes||0),0)} min`;$('#planDone').textContent=(acts||[]).filter(a=>pm.get(Number(a.id))).length;$('#planObjective').textContent=obj?.concursos_objetivos?.titulo||'Geral';$('#planStatus').textContent='PRONTO'}catch(e){console.error(e);$('#planStatus').textContent='INDISPONÍVEL';$('#planList').innerHTML='<div class="card empty">Não foi possível montar o plano agora. Seus dados permanecem preservados.</div>'}};$('#refreshPlan').onclick=render;await render()}
