import {sb} from './supabase.js';
const $=s=>document.querySelector(s);const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));const today=()=>new Date().toISOString().slice(0,10);
export async function loadReview(ctx){const uid=ctx.user.id;const [{data:errs},{data:cards},{data:revs},{data:favs},{data:resp}]=await Promise.all([sb.from('caderno_erros').select('questao_id,erros,dominado,questoes(id,enunciado,disciplina_id,assunto_id,disciplinas(nome),assuntos(nome))').eq('user_id',uid),sb.from('flashcards').select('id').eq('ativo',true),sb.from('flashcard_revisoes').select('flashcard_id,proxima_revisao,reviewed_at').eq('user_id',uid).order('reviewed_at',{ascending:false}),sb.from('favoritos').select('questao_id').eq('user_id',uid),sb.from('respostas').select('acertou,questao_id,questoes(assunto_id,disciplinas(nome),assuntos(nome))').eq('user_id',uid)]);
 const latest=new Map();for(const r of revs||[])if(!latest.has(Number(r.flashcard_id)))latest.set(Number(r.flashcard_id),r);const due=(cards||[]).filter(c=>{const r=latest.get(Number(c.id));return !r||!r.proxima_revisao||r.proxima_revisao<=today()}).length;const recurring=(errs||[]).filter(e=>!e.dominado&&Number(e.erros)>=2);const favCount=(favs||[]).length;
 const map=new Map();for(const r of resp||[]){const q=r.questoes;if(!q?.assunto_id)continue;const k=q.assunto_id,x=map.get(k)||{name:q.assuntos?.nome||'Assunto',disc:q.disciplinas?.nome||'',n:0,h:0};x.n++;if(r.acertou)x.h++;map.set(k,x)}const weak=[...map.values()].filter(x=>x.n>=3).map(x=>({...x,acc:Math.round(x.h/x.n*100)})).filter(x=>x.acc<70).sort((a,b)=>a.acc-b.acc);
 $('#reviewCards').innerHTML=[{i:'⚠️',t:'Erros recorrentes',n:recurring.length,d:'Questões erradas duas vezes ou mais.',href:'./questoes.html?modo=erros&quantidade=30'},{i:'🧠',t:'Flashcards vencidos',n:due,d:'Cartões programados para hoje.',href:'./flashcards.html'},{i:'📌',t:'Questões salvas',n:favCount,d:'Marcadas para revisar depois.',href:'./questoes.html?modo=favoritas&quantidade=30'},{i:'📉',t:'Assuntos abaixo de 70%',n:weak.length,d:'Com pelo menos 3 respostas registradas.',href:'./desempenho.html'}].map(x=>`<a class="card review-action-card" href="${x.href}"><span>${x.i}</span><div><b>${esc(x.t)}</b><small>${esc(x.d)}</small></div><strong>${x.n}</strong></a>`).join('');
 $('#reviewTopics').innerHTML=weak.length?weak.slice(0,6).map(x=>`<div class="review-line"><span><b>${esc(x.name)}</b><small>${esc(x.disc)} · ${x.n} respostas</small></span><strong>${x.acc}%</strong></div>`).join(''):'<div class="empty compact">Nenhum assunto com histórico suficiente abaixo de 70%.</div>';
 $('#reviewErrors').innerHTML=recurring.length?recurring.sort((a,b)=>b.erros-a.erros).slice(0,6).map(e=>`<div class="review-line"><span><b>${esc(e.questoes?.assuntos?.nome||e.questoes?.disciplinas?.nome||'Questão')}</b><small>${esc((e.questoes?.enunciado||'').slice(0,95))}${(e.questoes?.enunciado||'').length>95?'…':''}</small></span><a class="badge" href="./questoes.html?questao=${e.questao_id}">${e.erros} erros</a></div>`).join(''):'<div class="empty compact">Sem erros recorrentes pendentes.</div>';
}
