import {sb} from './supabase.js';
const $=s=>document.querySelector(s);let ctx,disc=[],assuntos=[],state=null,timer=null;
const key='missao_pe_active_study_session_v4';
const fmt=s=>`${String(Math.floor(s/3600)).padStart(2,'0')}:${String(Math.floor((s%3600)/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`;
function elapsed(){if(!state)return 0;return state.acc+(state.running?Math.floor((Date.now()-state.anchor)/1000):0)}
function paint(){const n=elapsed();$('#sessionClock').textContent=fmt(n);$('#sessionStatus').textContent=state?(state.running?'EM ANDAMENTO':'PAUSADA'):'PRONTA';$('#startSession').classList.toggle('hidden',!!state);$('#pauseSession').classList.toggle('hidden',!state||!state.running);$('#resumeSession').classList.toggle('hidden',!state||state.running);$('#finishSession').classList.toggle('hidden',!state);}
function save(){if(state)localStorage.setItem(key,JSON.stringify(state));else localStorage.removeItem(key)}
async function prefill(){const id=new URLSearchParams(location.search).get('ciclo_bloco');if(!id)return;const {data:b}=await sb.from('estudo_ciclo_blocos').select('*').eq('id',id).single();if(!b)return;$('#sessionDiscipline').value=b.disciplina_id;$('#sessionDiscipline').dispatchEvent(new Event('change'));$('#sessionSubject').value=b.assunto_id||'';$('#sessionType').value=b.tipo;$('#plannedMinutes').value=b.minutos_planejados;$('#cycleBlockId').value=b.id}
export async function loadSession(c){ctx=c;const [{data:d},{data:a}]=await Promise.all([sb.from('disciplinas').select('id,nome').order('nome'),sb.from('assuntos').select('id,nome,disciplina_id').order('nome')]);disc=d||[];assuntos=a||[];$('#sessionDiscipline').innerHTML='<option value="">Selecione</option>'+disc.map(x=>`<option value="${x.id}">${x.nome}</option>`).join('');$('#sessionDiscipline').onchange=()=>{$('#sessionSubject').innerHTML='<option value="">Conteúdo geral</option>'+assuntos.filter(x=>Number(x.disciplina_id)===Number($('#sessionDiscipline').value)).map(x=>`<option value="${x.id}">${x.nome}</option>`).join('')};await prefill();
 try{state=JSON.parse(localStorage.getItem(key)||'null')}catch{state=null} if(state&&state.user_id!==ctx.user.id)state=null;
 $('#startSession').onclick=()=>{if(!$('#sessionDiscipline').value)return alert('Selecione a disciplina.');state={user_id:ctx.user.id,start:new Date().toISOString(),anchor:Date.now(),acc:0,running:true,disciplina_id:Number($('#sessionDiscipline').value),assunto_id:$('#sessionSubject').value?Number($('#sessionSubject').value):null,tipo:$('#sessionType').value,ciclo_bloco_id:$('#cycleBlockId').value?Number($('#cycleBlockId').value):null};save();paint()};
 $('#pauseSession').onclick=()=>{state.acc=elapsed();state.running=false;save();paint()};$('#resumeSession').onclick=()=>{state.anchor=Date.now();state.running=true;save();paint()};
 $('#finishSession').onclick=async()=>{if(state.running)state.acc=elapsed();const sec=state.acc;if(sec<60&&!confirm('A sessão tem menos de 1 minuto. Deseja registrar mesmo assim?'))return;const {data:u}=await sb.from('usuario_objetivo').select('objetivo_id').eq('user_id',ctx.user.id).maybeSingle();const {error}=await sb.from('sessoes_estudo').insert({user_id:ctx.user.id,objetivo_id:u?.objetivo_id||null,ciclo_bloco_id:state.ciclo_bloco_id,disciplina_id:state.disciplina_id,assunto_id:state.assunto_id,tipo:state.tipo,iniciada_em:state.start,finalizada_em:new Date().toISOString(),duracao_liquida_segundos:sec,observacao:$('#sessionNote').value||null});if(error)return alert('Não foi possível salvar a sessão.');state=null;save();paint();$('#sessionSaved').textContent=`Sessão registrada: ${fmt(sec)} de estudo líquido.`;$('#sessionSaved').classList.remove('hidden')};
 timer=setInterval(paint,1000);window.addEventListener('pagehide',()=>clearInterval(timer),{once:true});paint()}
