import {sb} from './supabase.js';
const $=s=>document.querySelector(s);
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let ctx=null,materials=[],progress=new Map(),currentObjective=null,currentId=null;
function inline(v=''){let s=esc(v);s=s.replace(/\[\[(.+?)\]\]/g,'<mark class="theory-mark">$1</mark>');s=s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>');return s}
function pct(v){return Math.max(0,Math.min(100,Number(v)||0))}
function block(b){if(!b||typeof b!=='object')return'';const title=b.titulo?`<h3>${inline(b.titulo)}</h3>`:'';
 if(b.tipo==='texto')return`<section class="theory-block theory-text">${title}<p>${inline(b.texto||'')}</p></section>`;
 if(['destaque','bizu','mnemonico','pegadinha','lei'].includes(b.tipo)){const icon={destaque:'⭐',bizu:'💡',mnemonico:'🧠',pegadinha:'⚠️',lei:'⚖️'}[b.tipo];return`<section class="theory-callout ${b.tipo}"><div class="theory-callout-head"><span>${icon}</span><b>${esc(b.rotulo||({destaque:'ATENÇÃO',bizu:'BIZU',mnemonico:'MNEMÔNICO',pegadinha:'PEGADINHA DE PROVA',lei:'LEI / REGRA'}[b.tipo]))}</b></div>${title}<p>${inline(b.texto||'')}</p>${b.chave?`<div class="mnemonic-key">${inline(b.chave)}</div>`:''}</section>`}
 if(b.tipo==='termos'){return`<section class="theory-block"><h3>${inline(b.titulo||'Termos importantes')}</h3><div class="theory-terms">${(b.itens||[]).map(x=>`<div><mark>${inline(x.termo||'')}</mark><span>${inline(x.explicacao||'')}</span></div>`).join('')}</div></section>`}
 if(b.tipo==='lista')return`<section class="theory-block">${title}<ul class="theory-list">${(b.itens||[]).map(x=>`<li>${inline(x)}</li>`).join('')}</ul></section>`;
 if(b.tipo==='quadro'){const heads=b.colunas||[];return`<section class="theory-block">${title}<div class="table-wrap"><table class="theory-table"><thead><tr>${heads.map(x=>`<th>${inline(x)}</th>`).join('')}</tr></thead><tbody>${(b.linhas||[]).map(r=>`<tr>${r.map(x=>`<td>${inline(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`}
 if(b.tipo==='visual')return`<section class="theory-block theory-visual"><h3>${inline(b.titulo||'Mapa visual')}</h3>${b.texto?`<p>${inline(b.texto)}</p>`:''}<div class="visual-flow">${(b.itens||[]).map((x,i)=>`<div class="visual-node"><strong>${inline(x.titulo||String(i+1))}</strong><span>${inline(x.texto||'')}</span></div>`).join('<span class="visual-arrow">→</span>')}</div></section>`;
 if(b.tipo==='imagem'&&b.src)return`<figure class="theory-image"><img src="${esc(b.src)}" alt="${esc(b.alt||b.legenda||'Imagem de apoio')}">${b.legenda?`<figcaption>${inline(b.legenda)}</figcaption>`:''}</figure>`;
 if(b.tipo==='fixacao')return`<section class="theory-block"><h3>${inline(b.titulo||'Fixação rápida')}</h3><div class="fixation-list">${(b.itens||[]).map((x,i)=>`<details><summary>${i+1}. ${inline(x.pergunta||'')}</summary><p>${inline(x.resposta||'')}</p></details>`).join('')}</div></section>`;
 return''}
function filtered(){const q=($('#theorySearch')?.value||'').trim().toLowerCase(),did=Number($('#theoryDiscipline')?.value)||0,st=$('#theoryStatus')?.value||'todos';return materials.filter(m=>{const p=progress.get(Number(m.id)),done=p?.status==='concluido';if(did&&Number(m.disciplina_id)!==did)return false;if(st==='concluido'&&!done)return false;if(st==='pendente'&&done)return false;return !q||`${m.titulo||''} ${m.subtitulo||''} ${m.resumo||''} ${m.disciplinas?.nome||''} ${m.assuntos?.nome||''}`.toLowerCase().includes(q)})}
function renderList(){const list=filtered();$('#theoryCount').textContent=list.length;const host=$('#theoryList');if(!list.length){host.innerHTML='<div class="empty compact">Nenhum material encontrado.</div>';return}host.innerHTML=list.map(m=>{const p=progress.get(Number(m.id)),done=p?.status==='concluido';return`<button class="theory-list-item ${Number(currentId)===Number(m.id)?'active':''}" data-material="${m.id}" type="button"><span class="theory-list-state">${done?'✅':'📖'}</span><span><b>${esc(m.titulo)}</b><small>${esc(m.disciplinas?.nome||'')}${m.assuntos?.nome?' · '+esc(m.assuntos.nome):''}</small></span></button>`}).join('')}
async function markStarted(m){if(!m||progress.has(Number(m.id)))return;const payload={user_id:ctx.user.id,material_id:m.id,status:'em_estudo',progresso:10,iniciado_em:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await sb.from('teoria_leituras').upsert(payload,{onConflict:'user_id,material_id'});if(!error){progress.set(Number(m.id),payload);renderList()}if(currentObjective&&m.assunto_id){try{await sb.from('usuario_objetivo_assuntos').upsert({user_id:ctx.user.id,objetivo_id:currentObjective,assunto_id:m.assunto_id,status:'estudando',updated_at:new Date().toISOString()},{onConflict:'user_id,objetivo_id,assunto_id'})}catch{}}}
async function complete(m){const now=new Date().toISOString(),payload={user_id:ctx.user.id,material_id:m.id,status:'concluido',progresso:100,concluido_em:now,updated_at:now};const {error}=await sb.from('teoria_leituras').upsert(payload,{onConflict:'user_id,material_id'});if(error)return alert('Não foi possível registrar a conclusão.');progress.set(Number(m.id),payload);if(currentObjective&&m.assunto_id){try{await sb.from('usuario_objetivo_assuntos').upsert({user_id:ctx.user.id,objetivo_id:currentObjective,assunto_id:m.assunto_id,status:'estudado',estudado_em:now,updated_at:now},{onConflict:'user_id,objetivo_id,assunto_id'})}catch{}}renderList();renderReader(m)}
function renderReader(m){currentId=m.id;renderList();const p=progress.get(Number(m.id)),done=p?.status==='concluido';const qhref=`./questoes.html?disciplina=${m.disciplina_id}${m.assunto_id?`&assunto=${m.assunto_id}`:''}`;$('#theoryReader').innerHTML=`<header class="theory-reader-head"><div><span class="eyebrow">${esc(m.disciplinas?.nome||'TEORIA')}</span><h2>${esc(m.titulo)}</h2>${m.subtitulo?`<p>${inline(m.subtitulo)}</p>`:''}${m.assuntos?.nome?`<span class="badge">${esc(m.assuntos.nome)}</span>`:''}</div><span class="badge ${done?'ok':''}">${done?'CONCLUÍDO':'EM ESTUDO'}</span></header>${m.resumo?`<p class="theory-lead">${inline(m.resumo)}</p>`:''}<div class="theory-content">${(Array.isArray(m.blocos)?m.blocos:[]).map(block).join('')}</div>${m.fonte_nome||m.fonte_url?`<footer class="theory-source"><b>Fonte / referência</b><span>${inline(m.fonte_nome||'Referência do material')}</span>${m.fonte_url?`<a href="${esc(m.fonte_url)}" target="_blank" rel="noopener">ABRIR FONTE ↗</a>`:''}</footer>`:''}<div class="theory-reader-actions"><a class="btn secondary" href="${qhref}">📝 IR PARA QUESTÕES</a><button class="btn" id="completeTheory" type="button" ${done?'disabled':''}>${done?'✅ CONCLUÍDO':'MARCAR COMO ESTUDADO'}</button></div>`;$('#completeTheory')?.addEventListener('click',()=>complete(m));markStarted(m)}
async function load(){const [{data:uo},{data:m,error},{data:p}]=await Promise.all([sb.from('usuario_objetivo').select('objetivo_id,concursos_objetivos(titulo)').eq('user_id',ctx.user.id).maybeSingle(),sb.from('teoria_materiais').select('id,objetivo_id,disciplina_id,assunto_id,titulo,subtitulo,resumo,blocos,fonte_nome,fonte_url,ordem,disciplinas(nome),assuntos(nome,disciplina_id)').eq('ativo',true).order('ordem').order('titulo'),sb.from('teoria_leituras').select('material_id,status,progresso,concluido_em').eq('user_id',ctx.user.id)]);if(error)throw error;currentObjective=uo?.objetivo_id||null;$('#theoryObjective').textContent=uo?.concursos_objetivos?.titulo||'PREPARAÇÃO GERAL';materials=(m||[]).filter(x=>!x.objetivo_id||Number(x.objetivo_id)===Number(currentObjective));progress=new Map((p||[]).map(x=>[Number(x.material_id),x]));const discs=[...new Map(materials.map(x=>[x.disciplina_id,x.disciplinas?.nome])).entries()].sort((a,b)=>(a[1]||'').localeCompare(b[1]||''));$('#theoryDiscipline').innerHTML='<option value="">Todas as disciplinas</option>'+discs.map(([id,n])=>`<option value="${id}">${esc(n||'Disciplina')}</option>`).join('');renderList();const params=new URLSearchParams(location.search),mid=Number(params.get('material'))||0,aid=Number(params.get('assunto'))||0,did=Number(params.get('disciplina'))||0;let first=materials.find(x=>Number(x.id)===mid)||materials.find(x=>aid&&Number(x.assunto_id)===aid)||materials.find(x=>did&&Number(x.disciplina_id)===did&&!x.assunto_id)||materials.find(x=>did&&Number(x.disciplina_id)===did)||filtered()[0];if(first)renderReader(first)}
export async function setupTeoria(context){ctx=context;$('#theorySearch')?.addEventListener('input',renderList);$('#theoryDiscipline')?.addEventListener('change',renderList);$('#theoryStatus')?.addEventListener('change',renderList);$('#theoryList')?.addEventListener('click',e=>{const b=e.target.closest('[data-material]');if(!b)return;const m=materials.find(x=>Number(x.id)===Number(b.dataset.material));if(m)renderReader(m)});await load()}
